name: CI for Code Updates 

on:
  repository_dispatch:
    types: update-code-event

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Log
        run: echo "Running CI for Code Changes. Nothing configured. Please add 'update-code-event' to the list of events captured by main deploy.yaml Github Action." 
